### PR TITLE
Feature engineering.py

### PR DESCRIPTION
**Pull request by manoharkaranth**
This is the new feature engineering for Ad fraud problem on TalkingData dataset.

### CODE REVIEW

**Comment by arita37** [comment]
Cannot see any new features ?
What differences with previous feature ?

**Comment by manoharkaranth** [comment]
time before next click is added.

**Comment by manoharkaranth** [comment]
channel popularity, app popularity are also taken into account

**Comment by arita37** [comment]
So, can you just keep only new features.
It makes things clearer.

Time between past click is better.
(Cannot use future data).

**Comment by manoharkaranth** [comment]
Ok will do that

**Comment by manoharkaranth** [comment]
'base' inputs incorporated.
Also, found an error in the original file and debugged.

**Pull request merged**
